baseURL = 'https://forces-of-nature-rpg.io/'
languageCode = 'en-us'
title = 'Forces of Nature RPG'
theme = "hextra"

[[menu.main]]
name = "Home"
url = "/"
weight = 0

[[menu.main]]
name = "Societies"
url = "/societies/"
weight = 1

[[menu.main]]
name = "Search"
params = { type = "search" }

[[menu.main]]
name = "Theme Toggle"
params = { type = "theme-toggle", label = true }

[[menu.main]]
name = "Language switch"
params = { type = "language-switch", label = true, icon = "globe-alt"}
